apiVersion: v1
kind: Pod
spec:
  containers:
  - name: spark-driver
    env:
      - name: ATTESTATION
        value: false
      - name: ATTESTATION_URL
        value: your_attestation_url
      # - name: USING_LOCAL_DATA_KEY
      #   value: true
      # - name: LOCAL_DATA_KEY
      #   value: /ppml/encrypted_keys/plaintextkey
      # - name: ENCRYPTED_FSD
      #   value: true
      #- name: PCCS_URL
      #  value: your_pccs_url
      #- name: APP_ID
      #  valueFrom:
      #    secretKeyRef:
      #      name: kms-secret
      #      key: app_id
      #- name: API_KEY
      #  valueFrom:
      #    secretKeyRef:
      #      name: kms-secret
      #      key: app_key
      #- name: ATTESTATION_POLICYID
      #  valueFrom:
      #    secretKeyRef:
      #      name: kms-secret
      #      key: policy_id
      #- name: ATTESTATION_TYPE
      #  value: EHSMAttestationService
      #- name: QUOTE_TYPE
      #  value: gramine
    volumeMounts:
      - name: device-plugin
        mountPath: /var/lib/kubelet/device-plugins
      - name: aesm-socket
        mountPath: /var/run/aesmd/aesm.socket
      - name: nfs-storage
        mountPath: /ppml/data
      - name: secure-keys
        mountPath: /ppml/keys
      - name: kubeconfig
        mountPath: /root/.kube
      # - name: nfs-storage
      #   mountPath: /ppml/encrypted-fs
      #   subPath: encrypted-fs
      # - name: nfs-storage
      #   mountPath: /ppml/encrypted-fsd
      #   subPath: encrypted-fsd
      # - name: nfs-storage
      #   mountPath: /ppml/encrypted_keys
      #   subPath: test_keys
    resources:
      requests:
        cpu: 8
        memory: 32Gi
        sgx.intel.com/epc: 34359738368
        sgx.intel.com/enclave: 1
        sgx.intel.com/provision: 1
      limits:
        cpu: 10
        memory: 40Gi
        sgx.intel.com/epc: 34359738368
        sgx.intel.com/enclave: 1
        sgx.intel.com/provision: 1
  volumes:
    - name: device-plugin
      hostPath:
        path: /var/lib/kubelet/device-plugins
    - name: aesm-socket
      hostPath:
        path: /var/run/aesmd/aesm.socket
    - name: secure-keys
      secret:
        secretName: ssl-keys
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfsvolumeclaim
    - name: kubeconfig
      secret:
        secretName: kubeconfig-secret